version: '2.2'

networks:
  explorer:

services:
  frontend:
    image: nginx
    container_name: front
    tty: true
    ports:
      - 8080:80
    volumes: 
      - ./nginx-config/frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/var/www/html/frontend
    networks:
      - explorer

  backend:
    image: golang:latest
    container_name: back
    tty: true
    working_dir: /go/src/github.com/iost-official/backend
    command: ./scripts/start.sh
    stdin_open: true
    volumes: 
      - ./backend:/go/src/github.com/iost-official/backend
    networks:
      - explorer


  proxy:
    image: node:lts-alpine
    container_name: proxy
    tty: true
    ports:
      - 8000:8000
    command: ./start.sh
    stdin_open: true
    working_dir: /app/proxy/scripts
    volumes: 
      - ./proxy:/app/proxy
    networks:
      - explorer

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - explorer


