version: '2.2'

networks:
  explorer:

services:
  frontend:
    image: frontend:latest
    container_name: front
    ports:
      - 8080:8080
    command:
    volumes: 
      - ~/explorer/frontend/dist:/var/www/html/frontend
      - ~/explorer/nginx-config/frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - explorer

  backend:
    image: backend:latest
    container_name: back
    working_dir: /go/src/github.com/iost-official/explorer/backend
    tty: true
    networks:
      - explorer


  proxy:
    image: nginx
    container_name: proxy
    ports:
      - 10080:80
    command:
    volumes: 
      - ~/explorer/nginx-config/proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - explorer

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - explorer


